### ISSUE TITLE
Start fail

### ISSUE THREAD

**Issue by mostafabarmshory** [trello-desktop/trello#2]
I face with an exception:

```
npm ERR! Linux 4.1.15-8-default
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! trello@0.0.1 start: `electron dist/scripts/core.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the trello@0.0.1 start script 'electron dist/scripts/core.js'.
npm ERR! This is most likely a problem with the trello package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron dist/scripts/core.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls trello
npm ERR! There is likely additional logging output above.
```
Here is the log file:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@2.14.12
3 info using node@v4.2.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart trello@0.0.1
6 info start trello@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info trello@0.0.1 Failed to exec start script
9 verbose stack Error: trello@0.0.1 start: `electron dist/scripts/core.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/lib64/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/lib64/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid trello@0.0.1
11 verbose cwd /home/maso/Downloads/Tools/Trello/trello-master
12 error Linux 4.1.15-8-default
13 error argv "/usr/bin/node" "/usr/bin/npm" "start"
14 error node v4.2.4
15 error npm  v2.14.12
16 error code ELIFECYCLE
17 error trello@0.0.1 start: `electron dist/scripts/core.js`
17 error Exit status 1
18 error Failed at the trello@0.0.1 start script 'electron dist/scripts/core.js'.
18 error This is most likely a problem with the trello package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     electron dist/scripts/core.js
18 error You can get their info via:
18 error     npm owner ls trello
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

```

**Comment by ihgann** [comment]
This error is still prevalent.

**Comment by BuKinoshita** [comment]
Run gulp first
```bash
$ gulp
```

then `npm start`
